"""Perceiver — subgoal-conditioned multimodal observation distillation.

Replaces (raw screenshot + raw a11y) for the planner with a focused
``SubgoalSnapshot`` produced by a single VLM call per step.

Module layout:
  - dataclasses                    — SubgoalSnapshot + sub-types
  - renderer                       — to_prompt_block() for planner
  - perceive()                     — VLM call + parser + crop
  - _crop_screenshot               — given bbox, crop image bytes

See docs/PROGRESS_LEDGER_V2_CHANGELOG.md §17 for design context.
"""
from __future__ import annotations

import base64
import io
import json
import logging
import re
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Literal, Optional, Tuple

logger = logging.getLogger(__name__)


# --------------------------------------------------------------------------- #
# Data structures
# --------------------------------------------------------------------------- #

VerdictLiteral = Literal["yes", "no", "partial", "unknown"]
OverallVerdict = Literal["yes", "no", "partial"]
Coverage = Literal["complete", "partial"]


@dataclass
class ClauseCheck:
    """One sub-claim from the planner's expected_post_state, verified against
    the current screen by the perceiver.

    Each clause must carry concrete evidence (an a11y row quote, a bbox, or a
    URL substring) — perceiver is forbidden to hand-wave.
    """
    clause: str                 # auto-split from expected_post_state
    verdict: VerdictLiteral
    evidence: str               # a11y row / bbox / URL substring


@dataclass
class SubgoalCheck:
    """Turn-level verdict on the previous action's expected_post_state.

    Distinct from KeyNode's outcome state (task-level). This answers: did the
    very last planner subgoal achieve what it said it would?
    """
    overall: OverallVerdict
    clauses: List[ClauseCheck]


@dataclass
class Control:
    """One subgoal-relevant interactable element on the current screen.

    Perceiver picks ≤ 8 from the ~100-row prefiltered a11y candidate pool.
    Every entry must trace back to either an a11y row OR a vision_ocr bbox —
    no hallucinated controls.
    """
    label: str                                  # "Submit", "Jun 5", "Search bar (carl)"
    role: str                                   # "button", "textbox", "checkbox"
    state: List[str] = field(default_factory=list)
    # ["enabled"], ["checked", "focused"], ["disabled"], etc.
    value: Optional[str] = None                 # dropdown selected value, input current value
    bbox: Optional[Tuple[int, int, int, int]] = None  # (x1, y1, x2, y2) screen coords


@dataclass
class VisualFocus:
    """Mandatory visual companion to the text snapshot.

    A11y and vision must always double-anchor each other — each modality
    has independent failure modes, so the planner sees both every step.
    The crop is sized to encompass the relevant_controls bboxes (with
    padding), or falls back to the full screenshot when controls span
    too much of the screen.
    """
    bbox: Tuple[int, int, int, int]             # crop region in original screen coords
    crop_b64: str                               # base64-encoded PNG
    contains_controls: List[int]                # indices into relevant_controls inside crop
    out_of_crop_count: int                      # # of relevant_controls OUTSIDE the crop


@dataclass
class SlotBinding:
    """One unbound ledger slot the perceiver was able to resolve this step.

    Emitted by the perceiver only when the value is verbatim-visible in the
    current screenshot / a11y; perceiver MUST NOT guess or paraphrase. The
    planner promotes these into ``ledger.slots`` (bind-once) so downstream
    verify specs that reference ``${name}`` start running against a
    concrete value instead of short-circuiting to LLM judge.
    """
    name: str                # slot name (must exist in ledger.slots)
    value: str               # extracted verbatim from evidence
    evidence: str            # a11y row / bbox / quoted UI text justifying the value


@dataclass
class SubgoalSnapshot:
    """Replaces (raw screenshot + raw a11y) for the planner.

    Generated by one perceiver VLM call per step. ~600 tokens text + ~10-20KB
    crop image. Outcome state still flows through KeyNode → ledger; the
    snapshot here only carries perceiver-only fields (turn-level subgoal
    check, candidate controls, visual evidence, semantic transition,
    blockers, self-coverage assessment).
    """
    # Echo of the perceiver's input — so planner sees the query the
    # snapshot was conditioned on (paper-trail when debugging).
    subgoal_text: str
    expected_post_state: str

    # Five perceiver-only fields.
    subgoal_check: SubgoalCheck
    relevant_controls: List[Control]
    visual_focus: VisualFocus                   # required (always populated)
    transition_summary: str                     # ≤ 3 NL lines
    unexpected_blockers: List[str]
    coverage: Coverage

    # Slot bindings resolved this step (empty list when no slots were
    # unbound, or when none became readable in the current frame).
    # Planner promotes these to ledger.slots after the perceiver call.
    slot_bindings: List[SlotBinding] = field(default_factory=list)


# --------------------------------------------------------------------------- #
# Renderer
# --------------------------------------------------------------------------- #

_VERDICT_GLYPH = {
    "yes": "✓",
    "no": "✗",
    "partial": "~",
    "unknown": "?",
}


def _render_clause(clause: ClauseCheck) -> str:
    glyph = _VERDICT_GLYPH.get(clause.verdict, "?")
    # one-line summary + indented evidence so the planner sees both
    return (
        f"  {glyph} \"{clause.clause}\"\n"
        f"      → {clause.evidence}"
    )


def _render_control(idx: int, c: Control, in_crop: bool) -> str:
    state_str = f"[{', '.join(c.state)}]" if c.state else ""
    value_str = f" = {c.value!r}" if c.value else ""
    bbox_str = f" bbox={c.bbox}" if c.bbox else ""
    crop_marker = "← in crop" if in_crop else "← OUTSIDE crop"
    return (
        f"  [{idx + 1}] {c.role} {c.label!r} {state_str}{value_str}"
        f"{bbox_str}  {crop_marker}"
    )


def to_prompt_block(snap: SubgoalSnapshot) -> str:
    """Render the snapshot as a single text block for the planner.

    The visual_focus crop image is appended separately to the planner
    message as an image_url part. This function only renders text.
    """
    in_crop_set = set(snap.visual_focus.contains_controls)

    lines: List[str] = []
    lines.append("═══════ SCREEN SNAPSHOT (perceiver-distilled, subgoal-conditioned) ═══════")
    lines.append("")
    lines.append(f"▶ Current subgoal: {snap.subgoal_text}")
    lines.append(f"▶ Expected post-state: {snap.expected_post_state}")
    lines.append("")

    # ── SECTION: subgoal check ──
    lines.append("─── DID LAST ACTION ACHIEVE EXPECTED STATE? ───")
    lines.append(f"Overall: {snap.subgoal_check.overall.upper()}")
    if snap.subgoal_check.clauses:
        for clause in snap.subgoal_check.clauses:
            lines.append(_render_clause(clause))
    else:
        lines.append("  (no clauses extracted)")
    lines.append("")

    # ── SECTION: relevant controls ──
    lines.append("─── RELEVANT CONTROLS ───")
    if snap.relevant_controls:
        for idx, c in enumerate(snap.relevant_controls):
            lines.append(_render_control(idx, c, idx in in_crop_set))
    else:
        lines.append("  (none picked by perceiver)")
    lines.append("")

    # ── SECTION: transition ──
    lines.append("─── TRANSITION SINCE LAST TURN ───")
    lines.append(snap.transition_summary or "(no significant change)")
    lines.append("")

    # ── SECTION: blockers ──
    lines.append("─── BLOCKERS ───")
    if snap.unexpected_blockers:
        for b in snap.unexpected_blockers:
            lines.append(f"  • {b}")
    else:
        lines.append("  (none)")
    lines.append("")

    # ── SECTION: visual focus reference ──
    vf = snap.visual_focus
    n_in = len(vf.contains_controls)
    n_total = n_in + vf.out_of_crop_count
    lines.append("─── VISUAL EVIDENCE ───")
    lines.append(
        f"[CROP IMAGE attached above] bbox={vf.bbox}; "
        f"{n_in}/{n_total} relevant_controls visible in crop"
    )
    lines.append("")

    # ── SECTION: meta ──
    lines.append(f"─── PERCEIVER COVERAGE ───")
    lines.append(snap.coverage)

    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Perceiver prompt
# --------------------------------------------------------------------------- #

_PERCEIVER_SYSTEM_PROMPT = """You are the SCREEN PERCEIVER for a hierarchical GUI agent.

Each step you receive:
  - the current screenshot (full screen)
  - the current accessibility (a11y) tree (already coarsely filtered to
    likely-relevant rows; format: tag\\ttext\\tstate per row)
  - the agent's CURRENT subgoal (what it just tried to do)
  - the agent's expected_post_state (what should be true if the subgoal worked)
  - the active outcome ids and their evidence_hints
  - the actor's last action summary

Your job is to distill all of that into a single compact JSON snapshot
that the planner LLM will use to decide its next move. The planner will
NOT see the raw screenshot or a11y; it only sees your snapshot.

Output exactly two blocks, in this order:

<reasoning>
3-6 lines of brief reasoning. Cover:
  - Did the expected_post_state happen? Per clause yes/no/partial/unknown.
  - What controls on screen are RELEVANT to the subgoal (point to specific
    a11y rows or visual elements).
  - Is there anything visible on screen that is NOT in the a11y rows
    (modals/overlays/canvas widgets) that could affect the subgoal?
  - What changed since last turn?
</reasoning>

<json>
{
  "subgoal_check": {
    "overall": "yes" | "no" | "partial",
    "clauses": [
      {"clause": "<one atomic sub-claim of expected_post_state>",
       "verdict": "yes" | "no" | "partial" | "unknown",
       "evidence": "<quote a11y row OR cite bbox OR cite URL substring OR cite window-title / editor-tab text (the window or active editor tab name often names the file / workspace backing the current state — quote it verbatim)>"}
    ]
  },
  "relevant_controls": [
    {"label": "<visible label>", "role": "<button/textbox/...>",
     "state": ["enabled", "checked", ...],
     "value": "<current value or null>",
     "bbox": [x1, y1, x2, y2]}
    // 3-8 entries, ranked by subgoal relevance.
    // Each MUST appear in the input a11y rows OR be visible in screenshot.
  ],
  "visual_focus": {
    "bbox": [x1, y1, x2, y2],   // crop region in absolute screen pixels
    "rationale": "<why this region>"
    // The crop region should fully contain all relevant_controls and any
    // unexpected_blockers. If the subgoal-relevant area is unclear or the
    // a11y misses important visible UI, set bbox to the FULL SCREEN.
    // Better over-include than miss.
  },
  "transition_summary": "<2-3 NL sentences describing what changed since last turn; use noun phrases not verbs>",
  "unexpected_blockers": [
    "<NL description of any modal/popup/error/auth-wall blocking the subgoal>"
    // empty array if nothing blocking
  ],
  "coverage": "complete" | "partial",
  // 'partial' if any clause verdict is 'unknown' OR you suspect important
  // UI is not represented in either a11y or your relevant_controls.

  "slot_bindings": [
    // EMPTY array unless the user message contains an "UNRESOLVED VALUES"
    // section. When it does, each unresolved slot whose value is verbatim-
    // readable in the current screenshot / a11y becomes one entry:
    {"name": "<slot_name from the user message>",
     "value": "<the exact string the runtime should substitute — copy
               verbatim from a11y / screen; for URLs, the FULL href, not
               link text>",
     "evidence": "<a11y row OR bbox OR quoted UI text justifying value>"}
    // If a slot is referenced but you cannot extract a CONCRETE value
    // (only link text shown, value truncated, requires hover/right-click,
    // etc.), OMIT IT — do NOT guess. The planner will keep asking on
    // future steps.
  ]
}
</json>

Hard rules:
  • Each ClauseCheck.evidence MUST quote a real a11y row OR cite a bbox OR
    cite a URL substring OR quote a window-title / editor-tab text (e.g.
    "settings.json — Visual Studio Code", "project (Workspace)"). No
    prose-only verdicts.
  • Each Control MUST trace back to an a11y row (preferred) or a visible
    screen region (then mark its bbox from your visual reading). Don't
    invent controls.
  • visual_focus.bbox is REQUIRED. If unsure, return the full screen
    (e.g. [0, 0, screen_w, screen_h]).
  • A11y BLINDSPOT — desktop-app menus / dropdowns / command palettes /
    context menus / right-click menus often DO NOT appear in the a11y
    tree at all (especially in VS Code, LibreOffice, native GTK apps).
    When the subgoal expects such an overlay AND a11y has no matching
    row, do NOT default to "no" — switch to VISUAL inspection of the
    screenshot, cite the bbox where you see the overlay, and verdict
    accordingly. Conversely, if a11y shows nothing AND the screenshot
    also shows nothing, "no" is correct.
  • transition_summary uses noun phrases ("Date picker dialog opened")
    not verbs ("user clicked the Date field").
  • slot_bindings: copy values VERBATIM from the visible evidence. Never
    paraphrase, never guess from context. If the slot's referent appears
    on screen but its concrete value isn't exposed (e.g. only link text,
    not href), OMIT the slot from slot_bindings — that's a correct
    "I see it but cannot extract it" signal.
  • Keep reasoning under 6 lines. Keep the JSON tight."""


# --------------------------------------------------------------------------- #
# Image cropping helper
# --------------------------------------------------------------------------- #

def _crop_screenshot(
    screenshot_bytes: bytes,
    bbox: Tuple[int, int, int, int],
    max_long_edge: int = 800,
) -> Tuple[bytes, Tuple[int, int, int, int]]:
    """Crop the screenshot to the bbox and resize so the long edge ≤ max.

    Returns (png_bytes, sanitized_bbox).
    Sanitized bbox is clamped to image bounds.
    """
    try:
        from PIL import Image
    except ImportError as e:  # pragma: no cover
        raise RuntimeError("Pillow not installed") from e

    img = Image.open(io.BytesIO(screenshot_bytes))
    w, h = img.size

    x1, y1, x2, y2 = bbox
    # Sanitize: clamp to image, ensure x1<x2, y1<y2.
    x1 = max(0, min(int(x1), w - 1))
    y1 = max(0, min(int(y1), h - 1))
    x2 = max(x1 + 1, min(int(x2), w))
    y2 = max(y1 + 1, min(int(y2), h))

    crop = img.crop((x1, y1, x2, y2))

    # Resize so long edge ≤ max_long_edge to bound token cost.
    cw, ch = crop.size
    long_edge = max(cw, ch)
    if long_edge > max_long_edge:
        scale = max_long_edge / float(long_edge)
        nw, nh = int(cw * scale), int(ch * scale)
        crop = crop.resize((nw, nh), Image.LANCZOS)

    buf = io.BytesIO()
    crop.save(buf, format="PNG")
    return buf.getvalue(), (x1, y1, x2, y2)


# --------------------------------------------------------------------------- #
# Response parsing
# --------------------------------------------------------------------------- #

def _extract_json_block(raw: str) -> Optional[str]:
    """Pull the JSON object from the response. Tries <json> tag, then
    fenced ```json blocks, then the outermost balanced {...}.
    """
    if not raw:
        return None
    # 1. <json>...</json> (preferred — perceiver prompt asks for this)
    m = re.search(r"<json>\s*(.*?)\s*</json>", raw, re.DOTALL | re.IGNORECASE)
    if m:
        return m.group(1).strip()
    # 2. ```json ... ``` fenced block
    m = re.search(r"```(?:json)?\s*(\{.*\})\s*```", raw, re.DOTALL | re.IGNORECASE)
    if m:
        return m.group(1).strip()
    # 3. Outermost balanced {...} (fallback)
    s = raw.strip()
    start = s.find("{")
    if start < 0:
        return None
    depth = 0
    for i, ch in enumerate(s[start:], start=start):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return s[start:i + 1]
    return None


def _coerce_bbox(value: Any) -> Optional[Tuple[int, int, int, int]]:
    """Accept [x1,y1,x2,y2] (any number type). Return tuple of ints or None."""
    if not isinstance(value, (list, tuple)) or len(value) != 4:
        return None
    try:
        return tuple(int(v) for v in value)
    except (TypeError, ValueError):
        return None


def _rescale_bbox(
    bbox: Optional[Tuple[int, int, int, int]],
    *,
    src_size: Tuple[int, int],     # (w, h) the model is reasoning in
    dst_size: Tuple[int, int],     # (w, h) the actual screenshot
) -> Optional[Tuple[int, int, int, int]]:
    """Map a bbox from ``src_size`` (Qwen-VL's resized space) to
    ``dst_size`` (real screenshot pixels). Returns None if input is None
    or the source dimensions are degenerate."""
    if bbox is None:
        return None
    sw, sh = src_size
    dw, dh = dst_size
    if sw <= 0 or sh <= 0:
        return bbox
    fx, fy = dw / float(sw), dh / float(sh)
    x1, y1, x2, y2 = bbox
    return (int(round(x1 * fx)), int(round(y1 * fy)),
            int(round(x2 * fx)), int(round(y2 * fy)))


def _parse_snapshot(
    raw_response: str,
    *,
    subgoal_text: str,
    expected_post_state: str,
    screen_size: Tuple[int, int],          # ORIGINAL screenshot dims
    model_view_size: Optional[Tuple[int, int]] = None,   # what the model saw post-resize
    screenshot_bytes: bytes,
) -> Optional[SubgoalSnapshot]:
    """Parse the perceiver's raw text response into a SubgoalSnapshot.

    Bbox values in the response are interpreted as pixel coordinates in
    ``model_view_size`` (Qwen-VL's smart_resize space) and rescaled to
    ``screen_size`` (the real screenshot) before populating the
    SubgoalSnapshot — so downstream consumers (crop, planner) see real
    screen coords throughout.

    Returns None on any structural failure — caller should fall back to
    raw observations in that case.
    """
    # Default: no rescale (model_view == screen) — used by unit tests
    # with hand-crafted JSON in real-screen pixel space.
    if model_view_size is None:
        model_view_size = screen_size

    json_blob = _extract_json_block(raw_response)
    if not json_blob:
        logger.warning("[perceiver] no JSON block found in response")
        return None
    try:
        data = json.loads(json_blob)
    except json.JSONDecodeError as e:
        logger.warning("[perceiver] JSON parse error: %s", e)
        return None

    if not isinstance(data, dict):
        logger.warning("[perceiver] JSON is not an object: %s", type(data))
        return None

    # ── subgoal_check ──
    sc_raw = data.get("subgoal_check") or {}
    overall = sc_raw.get("overall", "unknown")
    if overall not in ("yes", "no", "partial"):
        overall = "partial"  # safest default

    clauses_out: List[ClauseCheck] = []
    for c in (sc_raw.get("clauses") or []):
        if not isinstance(c, dict):
            continue
        verdict = c.get("verdict", "unknown")
        if verdict not in ("yes", "no", "partial", "unknown"):
            verdict = "unknown"
        clauses_out.append(ClauseCheck(
            clause=str(c.get("clause", ""))[:240],
            verdict=verdict,
            evidence=str(c.get("evidence", ""))[:240],
        ))
    subgoal_check = SubgoalCheck(overall=overall, clauses=clauses_out)

    # ── relevant_controls ──
    # Each bbox is rescaled from model-view space to real screen pixels
    # so the planner sees coords matching the actual screenshot.
    controls_out: List[Control] = []
    for c in (data.get("relevant_controls") or [])[:8]:
        if not isinstance(c, dict):
            continue
        raw_bbox = _coerce_bbox(c.get("bbox"))
        bbox = _rescale_bbox(raw_bbox,
                              src_size=model_view_size,
                              dst_size=screen_size)
        state = c.get("state") or []
        if not isinstance(state, list):
            state = []
        controls_out.append(Control(
            label=str(c.get("label", ""))[:120],
            role=str(c.get("role", ""))[:40],
            state=[str(s)[:30] for s in state],
            value=(str(c["value"])[:120] if c.get("value") is not None else None),
            bbox=bbox,
        ))

    # ── visual_focus ──
    vf_raw = data.get("visual_focus") or {}
    raw_vf_bbox = _coerce_bbox(vf_raw.get("bbox"))
    if raw_vf_bbox is None:
        # Required field missing — fall back to full screen (real coords)
        vf_bbox = (0, 0, screen_size[0], screen_size[1])
        logger.warning("[perceiver] visual_focus.bbox missing — using full screen")
    else:
        vf_bbox = _rescale_bbox(raw_vf_bbox,
                                 src_size=model_view_size,
                                 dst_size=screen_size)

    # NOTE: physical cropping disabled — Qwen-VL's bbox precision is too
    # low to crop reliably (off-target crops were a worse signal than the
    # full screenshot). The planner attaches the full current frame via
    # the K-frame current-attach in _pa_call_planner, so we just override
    # visual_focus.bbox to FULL SCREEN here for honest accounting.
    # The perceiver's predicted bbox (already rescaled above) is dropped.
    vf_bbox = (0, 0, screen_size[0], screen_size[1])
    crop_b64 = ""

    # Compute contains_controls + out_of_crop_count from bbox membership
    contains: List[int] = []
    out_count = 0
    for i, ctl in enumerate(controls_out):
        if ctl.bbox and _bbox_intersects(ctl.bbox, vf_bbox):
            contains.append(i)
        else:
            out_count += 1

    visual_focus = VisualFocus(
        bbox=vf_bbox,
        crop_b64=crop_b64,
        contains_controls=contains,
        out_of_crop_count=out_count,
    )

    # ── transition / blockers / coverage ──
    transition = str(data.get("transition_summary") or "")[:600]
    blockers_raw = data.get("unexpected_blockers") or []
    if not isinstance(blockers_raw, list):
        blockers_raw = []
    blockers = [str(b)[:240] for b in blockers_raw]
    coverage = data.get("coverage", "partial")
    if coverage not in ("complete", "partial"):
        coverage = "partial"

    # ── slot_bindings ──
    # Each entry must have a non-empty ``name`` and ``value``; malformed
    # entries are dropped silently. Dedup by name keeping the FIRST
    # occurrence (perceiver shouldn't emit dupes, but if it does, prefer
    # the first one since the second is likely a re-statement).
    slot_bindings_out: List[SlotBinding] = []
    seen_names: set = set()
    for sb in (data.get("slot_bindings") or []):
        if not isinstance(sb, dict):
            continue
        name = str(sb.get("name") or "").strip()
        value = sb.get("value")
        if value is None:
            continue
        value = str(value).strip()
        if not name or not value or name in seen_names:
            continue
        seen_names.add(name)
        slot_bindings_out.append(SlotBinding(
            name=name[:60],
            value=value[:512],
            evidence=str(sb.get("evidence") or "")[:240],
        ))

    return SubgoalSnapshot(
        subgoal_text=subgoal_text,
        expected_post_state=expected_post_state,
        subgoal_check=subgoal_check,
        relevant_controls=controls_out,
        visual_focus=visual_focus,
        transition_summary=transition,
        unexpected_blockers=blockers,
        coverage=coverage,
        slot_bindings=slot_bindings_out,
    )


def _bbox_intersects(a: Tuple[int, int, int, int],
                     b: Tuple[int, int, int, int]) -> bool:
    """Return True if rectangles a and b overlap (any pixel)."""
    ax1, ay1, ax2, ay2 = a
    bx1, by1, bx2, by2 = b
    return not (ax2 <= bx1 or bx2 <= ax1 or ay2 <= by1 or by2 <= ay1)


# --------------------------------------------------------------------------- #
# Public entry point
# --------------------------------------------------------------------------- #

def perceive(
    *,
    screenshot_bytes: bytes,
    screen_size: Tuple[int, int],     # ORIGINAL screen pixel size (orig_w, orig_h)
    a11y_text: str,
    subgoal_text: str,
    expected_post_state: str,
    target_outcomes: List[Any],   # objects with .id, .evidence_hint
    last_action_summary: str,
    transition_block: str,        # already-rendered a11y delta or NL summary
    call_llm: Callable,
    model: Optional[str] = None,
    max_tokens: int = 1500,
    raw_sink: Optional[Callable[[str], None]] = None,   # capture raw response for debug
    unbound_slots: Optional[List[Any]] = None,   # ledger Slot objects (.name/.type/.description/.source_hint)
) -> Optional[SubgoalSnapshot]:
    """Run the perceiver: 1 LLM call, parse, return SubgoalSnapshot.

    Returns None on LLM failure or parse failure — caller should fall
    back to raw screenshot + raw a11y for the planner.
    """
    # Tiny helper local-scoped: prefix the a11y rows with the shared
    # state-column legend so the perceiver doesn't have to remember
    # 'enabled' vs 'selected' semantics from the system prompt.
    def _format_a11y_with_legend(rows: str, *, label: str) -> str:
        from mm_agents.structagent.ledger.support.a11y_legend import with_legend
        return with_legend(rows or "", header=f"{label} (tag\\ttext\\tstate):")

    # Compute the dimensions Qwen-VL will actually see post smart_resize.
    # We tell the perceiver this dimension as 'screen size' so its bbox
    # outputs are in the same space the model is reasoning in. Parser
    # rescales those bboxes back to ``screen_size`` (real screenshot).
    try:
        from mm_agents.structagent.utils.image import smart_resize
        model_view_h, model_view_w = smart_resize(
            screen_size[1], screen_size[0],
        )
    except Exception:
        # Fallback: use original size (no rescale)
        model_view_h, model_view_w = screen_size[1], screen_size[0]
    model_view_size = (int(model_view_w), int(model_view_h))

    user_text_parts: List[str] = []

    # Screen size so the perceiver knows the bbox space it should output in.
    # IMPORTANT: this is the model-view dimensions (post smart_resize),
    # NOT the original screenshot dims. The runtime rescales bboxes back.
    user_text_parts.append(
        f"Screen size (w x h): {model_view_size[0]} x {model_view_size[1]}"
    )

    # Subgoal context
    user_text_parts.append(f"Current subgoal:\n  {subgoal_text}")
    user_text_parts.append(f"Expected post-state:\n  {expected_post_state}")
    user_text_parts.append(f"Actor's last action: {last_action_summary}")

    # Active outcomes with evidence hints
    if target_outcomes:
        oc_lines = ["Active task outcomes (verify against these):"]
        for o in target_outcomes:
            oid = getattr(o, "id", "?")
            hint = getattr(o, "evidence_hint", "")
            oc_lines.append(f"  - {oid}: {hint}")
        user_text_parts.append("\n".join(oc_lines))

    # A11y rows (prefiltered)
    user_text_parts.append(
        _format_a11y_with_legend(a11y_text, label="A11y tree (subgoal-prefiltered)")
    )

    # Transition info (delta or NL summary from previous turn)
    if transition_block:
        user_text_parts.append(f"Transition since last turn:\n{transition_block}")

    # Unresolved ledger slots — only rendered when present, so slot-free
    # tasks pay zero prompt overhead. The system prompt's slot_bindings
    # contract activates only when this section is included.
    if unbound_slots:
        slot_lines = [
            "UNRESOLVED VALUES (ledger needs these to verify outcomes):",
        ]
        for s in unbound_slots:
            name = getattr(s, "name", "?")
            stype = getattr(s, "type", "text")
            desc = getattr(s, "description", "") or ""
            hint = getattr(s, "source_hint", "") or ""
            slot_lines.append(f"  - ${{{name}}} ({stype}): {desc}")
            if hint:
                slot_lines.append(f"      hint: {hint}")
        slot_lines.append(
            "For each slot whose CONCRETE value is verbatim-readable on the "
            "current screen / a11y, emit a slot_bindings entry. If only the "
            "referent is visible (e.g. link text without href, truncated "
            "value), OMIT — never guess."
        )
        user_text_parts.append("\n".join(slot_lines))

    # Build messages: image first, then text
    user_content: List[Dict[str, Any]] = []
    if screenshot_bytes:
        b64 = base64.b64encode(screenshot_bytes).decode("ascii")
        user_content.append({
            "type": "image_url",
            "image_url": {"url": f"data:image/png;base64,{b64}"},
        })
    user_content.append({"type": "text", "text": "\n\n".join(user_text_parts)})

    messages = [
        {"role": "system", "content": _PERCEIVER_SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]

    try:
        raw = call_llm(
            {"model": model, "messages": messages,
             "max_tokens": max_tokens, "temperature": 0.0, "top_p": 0.9},
            model,
        )
    except Exception as e:
        logger.warning("[perceiver] LLM call failed: %s", e)
        return None
    if not raw:
        logger.warning("[perceiver] LLM returned empty")
        return None

    # Notify raw-sink BEFORE parsing so debug dumps survive parse failures
    if raw_sink is not None:
        try:
            raw_sink(raw)
        except Exception as e:
            logger.info("[perceiver] raw_sink raised: %s", e)

    return _parse_snapshot(
        raw,
        subgoal_text=subgoal_text,
        expected_post_state=expected_post_state,
        screen_size=screen_size,
        model_view_size=model_view_size,
        screenshot_bytes=screenshot_bytes,
    )


# --------------------------------------------------------------------------- #
# Environment perceiver — once per task
# --------------------------------------------------------------------------- #
#
# The same digestion idea as ``perceive`` (which compresses the per-step
# a11y tree by subgoal context), applied to the VM's task-start
# environment probe (binaries, config files, GSettings schema pool,
# processes). It runs ONCE per task at init_ledger time and produces a
# small text block that the ledger initializer + planner consume.
#
# The probe itself (see ``probes.py``) is task-agnostic — it knows
# nothing about the user's instruction. THIS function is where the
# task-conditioned filtering happens, so the prompt downstream sees a
# focused subset rather than 400+ schemas plus 20 paths.

_ENVIRONMENT_PERCEIVER_PROMPT = """You are the ENVIRONMENT PERCEIVER. The
user has given a task instruction. You also see a raw probe of the VM
captured at task start: identity, available binaries, app config-file
locations, the full GNOME GSettings schema pool, and current-running
processes.

Your job is to compress the probe into a compact context block that
keeps ONLY the items potentially useful for completing this specific
task, and drops the irrelevant majority. The downstream ledger
initializer and planner will read your output to ground their
decisions (which schema to query, which binary to invoke, which file
to edit, …) — they will NOT see the raw probe.

Hard rules:
  • NEVER invent any identifier (schema, binary, path, process) that
    is NOT verbatim in the raw probe. Filter and rephrase only.
  • Recall > precision. When uncertain whether an item is relevant,
    KEEP it. Missing a relevant schema is worse than including an
    extra one.
  • Quote schemas / paths / binary names exactly as the probe spelled
    them.

Output exactly this plain-text shape (no JSON, no markdown headers):

  [Identity]
  user=<from probe>  home=<from probe>  os=<from probe NAME if shown>

  [Relevant binaries]   (omit section if none look task-relevant)
    <binary> -> <path>
    <binary> -> NOT_FOUND
    ...
  ── Standard POSIX tools (cp, mv, rm, mkdir, ls, find, sed, awk,
     grep, cat, echo, tr, sort, uniq, cut, wc, tee, tar, gzip, chmod,
     chown, etc.) are universally available on Ubuntu and MAY be used
     by the downstream agent even if a specific one isn't enumerated
     in the probe's binaries section. Do NOT mark them as missing or
     omit them from your reasoning. Mention them in this section ONLY
     if the task specifically revolves around one of them (e.g. the
     task is literally "use sed to ...").

  [Relevant config files]   (omit if none)
    <absolute path>  (existed: yes|no)

  [Possibly useful files]   (omit if none; user documents under
                             Desktop / Documents / Downloads the task
                             may need to open or edit)
    <absolute path>
    ...
  ── Source these ONLY from the probe's "### user dirs" listing; quote
     each absolute path VERBATIM (never invent or guess a path).
  ── Keep a file ONLY when its name plausibly matches THIS task's
     subject — the document/spreadsheet/archive the instruction refers
     to. DROP everything unrelated (silently — do not explain). If the
     probe listed many files and only one matches the task, emit only
     that one. If none match, omit the whole section.
  ── When ONE file's name is an exact / near-exact match for the
     document the instruction explicitly names, emit that file ALONE —
     do NOT also add files that merely share a single theme word with
     the task. List several only when the target is genuinely
     ambiguous.
  ── These files are NOT open yet. The downstream agent should open one
     directly with the ``open_app`` action — ``open_app(app=<app>,
     file=<absolute path>)`` — instead of hunting through the GUI file
     picker; that avoids mis-clicks and opening a blank document by
     mistake.

  [Relevant GSettings schemas]   (omit if the task has no system-setting flavor)
    <schema-1>
      keys: <only the keys whose name suggests they back this task — comma-separated>
    <schema-2>
      keys: <subset of schema-2's keys relevant to this task>
    ...
  ── If the probe's `gsettings list-keys` command line for a schema
     ended with a `:<dconf-path>` suffix (i.e. the schema is
     relocatable — defined statically but addressed by a runtime
     dconf path), include that `:<dconf-path>` suffix verbatim as
     part of the schema name in your output. Otherwise `gsettings
     get/set` fails with "Schema ... is relocatable (path must be
     specified)". Copy the suffix EXACTLY as it appeared in the probe.
  ── For each task-relevant schema, list ONLY the keys (from the probe's
     list-keys section) that plausibly back the task. Drop keys whose
     name is clearly unrelated. If the probe shows a schema HAS no
     plausibly-relevant key, DROP that schema entirely — including a
     schema with no usable key just misleads the downstream LLM.
  ── HARD RULE: if the probe's list-keys section did NOT enumerate keys
     for a schema (you can see no "schema=<name>" block for it under
     "### gsettings keys"), you MUST write `keys: (probe did not list)`
     — NEVER invent keys from training memory. Hallucinated keys lead
     to verifier commands that always fail.
  ── Do NOT include schemas, binaries, or items as "dropped because ..."
     — if you are dropping it, simply OMIT it. Do not explain.

  [Relevant dconf paths]   (omit if none; only include when the probe's
                            "### dconf dump …" section contains a
                            line directly relevant to this task)
    <full dconf path, including any UUID-instanced segment>=<value-from-dump>
    <full dconf path>=<value-from-dump>
    ...
  ── Some settings (notably GNOME Terminal profiles) live at dconf
     paths that DO NOT appear in `gsettings list-schemas`. The dconf
     dump section is your only source for them. Quote the exact path
     (with any UUID) verbatim; the downstream LLM will need it to
     construct the `gsettings get/set <schema>:<dconf-path>` form.
  ── If the dconf dump section is EMPTY but a related UUID is visible
     elsewhere in the probe (e.g. the gnome-terminal probe section
     lists ``default-profile-uuid: 'xxx-yyy-zzz'``), write the path
     using that REAL UUID. If no UUID is visible anywhere in the
     probe, OMIT the entry — NEVER write `<UUID>` or any placeholder.

  [Running processes]   (only if the task is about a running app)
    <line from pgrep>

Keep total output ≤ 1500 characters. End with a single empty line."""


# Domain-conditional perceiver schema. Appended to
# :data:`_ENVIRONMENT_PERCEIVER_PROMPT` only when the task's domain
# matches. These blocks define an ADDITIONAL output section and route
# domain entries into it — the WHY (storage conventions, allowed
# verify shapes, …) lives in the corresponding domain_knowledge file
# and is injected into the planner / init_ledger separately.
_VLC_PERCEIVER_RULES = """

  [VLC config]   (this task's domain is VLC; emit when the probe has a
                  `### vlc config` section)
    path: <path-from-probe>  (<exists | not yet present>)
    <key>=<value>   ← copy each task-relevant active line VERBATIM from
                      the probe's "active key=value lines" block; if no
                      lines are listed, emit only the path line.

  ── All VLC-related items go in [VLC config]. Do NOT route VLC entries
     into [Relevant GSettings schemas] or [Relevant dconf paths]."""


_LIBREOFFICE_PERCEIVER_RULES = """

  [LibreOffice / Python office libs]   (this task's domain is one of
                                         libreoffice_writer / impress /
                                         calc; emit when the probe has
                                         a `### libreoffice` section)
    soffice version: <version line from probe, or "not installed">
    python-docx:     <version, or "not available">
    openpyxl:        <version, or "not available">
    python-pptx:     <version, or "not available">

  ── These versions tell the downstream agent whether the python3 -c
     verify shape is usable for this task's document type. If
     python-docx is available, .docx tasks can use shell_command
     ["python3", "-c", "..."] verify specs and python-docx-driven
     cli_run edits. If not, fall back to a11y / GUI."""


_DOMAIN_PERCEIVER_RULES = {
    "vlc":                 _VLC_PERCEIVER_RULES,
    "libreoffice_writer":  _LIBREOFFICE_PERCEIVER_RULES,
    "libreoffice_calc":    _LIBREOFFICE_PERCEIVER_RULES,
    "libreoffice_impress": _LIBREOFFICE_PERCEIVER_RULES,
}


def _build_perceiver_prompt(domain: Optional[str]) -> str:
    tail = _DOMAIN_PERCEIVER_RULES.get((domain or "").lower().strip(), "")
    return _ENVIRONMENT_PERCEIVER_PROMPT + tail if tail else _ENVIRONMENT_PERCEIVER_PROMPT


def perceive_environment(
    *,
    instruction: str,
    probe_text: str,
    call_llm,
    model: Optional[str] = None,
    domain: Optional[str] = None,
    max_tokens: int = 800,
) -> Optional[str]:
    """Once-per-task: filter the raw probe down to task-relevant items.

    Returns the digested context block (plain text, ≤ ~1.5KB) or ``None``
    on LLM failure / empty input. Caller decides whether to fall back to
    raw probe text or omit the section entirely.

    When ``domain`` matches a known per-domain block (currently
    ``"vlc"``), the block is appended to the system prompt so the
    perceiver knows the additional output section to emit. The full
    domain conventions are NOT repeated here — they ship in the
    corresponding domain_knowledge file injected into the planner.
    """
    if not probe_text or not probe_text.strip():
        return None
    system_prompt = _build_perceiver_prompt(domain)
    user_text = (
        f"Task instruction:\n{instruction.strip()}\n\n"
        f"Raw VM probe at task start:\n```\n{probe_text}\n```\n\n"
        "Output the compact context block now. Filter only — never invent."
    )
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_text},
        ],
        "max_tokens": max_tokens,
        "temperature": 0.0,
        "top_p": 0.9,
    }
    try:
        out = call_llm(payload, model)
    except Exception as e:
        logger.warning("[env-perceiver] LLM call failed: %s", e)
        return None
    if not out or not out.strip():
        logger.info("[env-perceiver] empty output")
        return None
    return out.strip()
